class Color:
    def __init__(self, name, emoji):
        self.name = name
        self.emoji = emoji


supported_colors = [
    Color("Red", "🔴"),
    Color("Blue", "🔵"),
    Color("Yellow", "🟡"),
    Color("Green", "🟢"),
    Color("Orange", "🟠"),
    Color("Purple", "🟣"),
    Color("Brown", "🟤"),
    Color("Black", "⚫")
]

supported_languages = [
    "Afrikaans",
    "Arabic",
    "Amharic",
    "Armenian",
    "Azerbaijani",
    "Baniya",
    "Belarusian",
    "Bengali",
    "Bulgarian",
    "Burmese",
    "Cantonese",
    "Czech",
    "Danish",
    "Dutch",
    "Estonian",
    "Farsi",
    "Filipino",
    "Finnish",
    "French",
    "Garhwali",
    "Georgian",
    "German",
    "Greek",
    "Gujarati",
    "Hebrew",
    "Hindustani",
    "Hungarian",
    "Italian",
    "Indonesian",
    "Japanese",
    "Kannada",
    "Kazakh",
    "Korean",
    "Kurdish",
    "Kyrgyz",
    "Latvian",
    "Lithuanian",
    "Malay",
    "Malayalam",
    "Mandarin",
    "Marathi",
    "Mizo",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Pashto",
    "Persian",
    "Portuguese (PT/BR)",
    "Polish",
    "Russian",
    "Punjabi",
    "Romanian",
    "Sindhi",
    "Serbian",
    "Spanish",
    "Sinhala",
    "Slovak",
    "Slovene",
    "Somali",
    "Swahili",
    "Swedish",
    "Taiwanese",
    "Tamil",
    "Telugu",
    "Thai",
    "Turkish",
    "Vietnamese",
    "Tulu",
    "Ukrainian",
    "Walloon",
    "Welsh",
    "Zulu"
]
